modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0"

[[mods]]
modId = "handycam"
version = "${version}"
displayName = "Handycam"
displayURL = "https://modrinth.com/mod/handycam"
authors = "vercim"
description = '''
Cinematic camera shake for Minecraft — idle drift, walk bob, landing impact, damage hit, and sprint sway.
'''

[[dependencies.handycam]]
modId = "neoforge"
type = "required"
versionRange = "[21.4.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.handycam]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.handycam]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.handycam]]
modId = "cloth_config"
type = "required"
versionRange = "[17,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "handycam.mixins.json"
